server.port=8082

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_platform_payment_service
spring.datasource.username=root
spring.datasource.password=${PAYMENT_DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Swagger
springdoc.swagger-ui.tagsSorter=alpha

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=payment-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.yashmerino.ecommerce.kafka.events
spring.kafka.consumer.properties.spring.json.type.mapping=PaymentRequestedEvent:com.yashmerino.ecommerce.kafka.events.PaymentRequestedEvent
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Stripe
stripe.api.key=${STRIPE_API_KEY}

# V2 Topics
payment.topics.payment-requested-v2=payment.requested.v2
payment.topics.payment-result-v2=payment.result.v2
payment.topics.payment-review-v2=payment.review.required.v2
payment.topics.refund-requested-v2=payment.refund.requested.v2
payment.topics.refund-result-v2=payment.refund.result.v2
payment.topics.notification-requested-v2=notification.requested.v2

# Outbox
outbox.poll-interval-ms=2000
outbox.poll-size=10
outbox.lease-seconds=30

# Payment Worker
payment.worker.poll-interval-ms=1000
payment.worker.poll-size=5
payment.worker.lease-seconds=30
payment.worker.stripe-timeout-seconds=30
