CREATE TABLE commission_rules (
    id BIGINT NOT NULL AUTO_INCREMENT,
    partner_id BIGINT DEFAULT NULL,
    category_id BIGINT DEFAULT NULL,
    product_id BIGINT DEFAULT NULL,
    rate DECIMAL(5,4) NOT NULL,
    fixed_fee DECIMAL(19,2) DEFAULT 0.00,
    currency VARCHAR(3) DEFAULT NULL,
    valid_from DATETIME(6) DEFAULT NULL,
    valid_to DATETIME(6) DEFAULT NULL,
    priority INT NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    version BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_commission_partner (partner_id),
    KEY idx_commission_category (category_id),
    KEY idx_commission_product (product_id),
    KEY idx_commission_status (status)
) ENGINE=InnoDB;

CREATE TABLE settlements (
    id BIGINT NOT NULL AUTO_INCREMENT,
    partner_id BIGINT NOT NULL,
    period_start DATETIME(6) NOT NULL,
    period_end DATETIME(6) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'USD',
    gross_sales DECIMAL(19,2) NOT NULL DEFAULT 0.00,
    refund_amount DECIMAL(19,2) NOT NULL DEFAULT 0.00,
    commission_amount DECIMAL(19,2) NOT NULL DEFAULT 0.00,
    other_fees DECIMAL(19,2) NOT NULL DEFAULT 0.00,
    manual_adjustment DECIMAL(19,2) NOT NULL DEFAULT 0.00,
    payable_amount DECIMAL(19,2) NOT NULL DEFAULT 0.00,
    status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    approved_by BIGINT DEFAULT NULL,
    approved_at DATETIME(6) DEFAULT NULL,
    paid_at DATETIME(6) DEFAULT NULL,
    payment_reference VARCHAR(255) DEFAULT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_settlement_partner (partner_id),
    KEY idx_settlement_status (status),
    KEY idx_settlement_period (partner_id, period_start, period_end),
    CONSTRAINT fk_settlement_partner FOREIGN KEY (partner_id) REFERENCES partners(id),
    CONSTRAINT fk_settlement_approved_by FOREIGN KEY (approved_by) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE settlement_lines (
    id BIGINT NOT NULL AUTO_INCREMENT,
    settlement_id BIGINT NOT NULL,
    partner_id BIGINT NOT NULL,
    line_type VARCHAR(30) NOT NULL,
    order_id BIGINT DEFAULT NULL,
    partner_order_id BIGINT DEFAULT NULL,
    refund_id BIGINT DEFAULT NULL,
    amount DECIMAL(19,2) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'USD',
    description VARCHAR(500) DEFAULT NULL,
    adjustment_reason VARCHAR(1000) DEFAULT NULL,
    created_by BIGINT DEFAULT NULL,
    idempotency_key VARCHAR(255) DEFAULT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_settlement_line_idempotency (idempotency_key),
    KEY idx_settlement_line_settlement (settlement_id),
    KEY idx_settlement_line_partner (partner_id),
    CONSTRAINT fk_settlement_line_settlement FOREIGN KEY (settlement_id) REFERENCES settlements(id),
    CONSTRAINT fk_settlement_line_partner FOREIGN KEY (partner_id) REFERENCES partners(id)
) ENGINE=InnoDB;
