CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT NOT NULL AUTO_INCREMENT,
    order_id BIGINT NOT NULL,
    product_id BIGINT,
    offer_id BIGINT,
    partner_id BIGINT,
    partner_order_id BIGINT,
    name VARCHAR(255) NOT NULL,
    unit_price DECIMAL(19,2) NOT NULL,
    quantity INT NOT NULL,
    product_discount DECIMAL(19,2) NOT NULL DEFAULT 0.00,
    order_discount_allocation DECIMAL(19,2) NOT NULL DEFAULT 0.00,
    coupon_discount_allocation DECIMAL(19,2) NOT NULL DEFAULT 0.00,
    redeemed_point_allocation DECIMAL(19,2) NOT NULL DEFAULT 0.00,
    discount_allocation DECIMAL(19,2) NOT NULL DEFAULT 0.00,
    shipping_allocation DECIMAL(19,2) NOT NULL DEFAULT 0.00,
    line_total DECIMAL(19,2) NOT NULL,
    qualifying_amount DECIMAL(19,2) NOT NULL,
    is_gift BOOLEAN NOT NULL DEFAULT FALSE,
    partner_name VARCHAR(255),
    partner_sku VARCHAR(100),
    commission_rule_id BIGINT,
    commission_rate DECIMAL(5,4),
    commission_fixed_fee DECIMAL(19,2),
    commission_amount DECIMAL(19,2),
    partner_payable_amount DECIMAL(19,2),
    currency VARCHAR(3) NOT NULL DEFAULT 'VND',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_order_item_order (order_id),
    KEY idx_order_item_partner (partner_id),
    KEY idx_order_item_offer (offer_id),
    KEY idx_order_item_partner_order (partner_order_id),
    CONSTRAINT fk_order_item_order_v20 FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_order_item_product_v20 FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_order_item_offer_v20 FOREIGN KEY (offer_id) REFERENCES partner_offers(id),
    CONSTRAINT fk_order_item_partner_v20 FOREIGN KEY (partner_id) REFERENCES partners(id),
    CONSTRAINT fk_order_item_partner_order_v20 FOREIGN KEY (partner_order_id) REFERENCES partner_orders(id),
    CONSTRAINT chk_order_item_quantity_v20 CHECK (quantity > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
