CREATE TABLE partner_orders (
    id BIGINT NOT NULL AUTO_INCREMENT,
    order_id BIGINT NOT NULL,
    partner_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'NEW',
    subtotal DECIMAL(19,2) NOT NULL DEFAULT 0.00,
    discount_allocation DECIMAL(19,2) NOT NULL DEFAULT 0.00,
    shipping_allocation DECIMAL(19,2) NOT NULL DEFAULT 0.00,
    commission_amount DECIMAL(19,2) NOT NULL DEFAULT 0.00,
    partner_payable_amount DECIMAL(19,2) NOT NULL DEFAULT 0.00,
    currency VARCHAR(3) NOT NULL DEFAULT 'USD',
    accepted_at DATETIME(6),
    rejected_at DATETIME(6),
    rejection_reason VARCHAR(1000),
    packed_at DATETIME(6),
    ready_to_ship_at DATETIME(6),
    shipped_at DATETIME(6),
    delivered_at DATETIME(6),
    cancelled_at DATETIME(6),
    cancel_reason VARCHAR(1000),
    version BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_partner_order (order_id, partner_id),
    KEY idx_partner_order_partner_status (partner_id, status),
    KEY idx_partner_order_order (order_id),
    CONSTRAINT fk_partner_order_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_partner_order_partner FOREIGN KEY (partner_id) REFERENCES partners(id),
    CONSTRAINT chk_partner_order_status CHECK (status IN ('NEW','ACCEPTED','REJECTED','PACKING','READY_TO_SHIP','SHIPPED','DELIVERED','CANCELLED','RETURN_REQUESTED','RETURNED'))
) ENGINE=InnoDB;

ALTER TABLE order_items
    ADD COLUMN partner_id BIGINT DEFAULT NULL,
    ADD COLUMN offer_id BIGINT DEFAULT NULL,
    ADD COLUMN partner_sku VARCHAR(100) DEFAULT NULL,
    ADD COLUMN commission_rule_id BIGINT DEFAULT NULL,
    ADD COLUMN commission_rate DECIMAL(5,4) DEFAULT NULL,
    ADD COLUMN commission_fixed_fee DECIMAL(19,2) DEFAULT NULL,
    ADD COLUMN commission_amount DECIMAL(19,2) DEFAULT NULL,
    ADD COLUMN partner_payable_amount DECIMAL(19,2) DEFAULT NULL,
    ADD KEY idx_order_item_partner (partner_id),
    ADD KEY idx_order_item_offer (offer_id);
