CREATE TABLE payment_operations (
    id BIGINT NOT NULL AUTO_INCREMENT,
    main_payment_id BIGINT,
    order_id BIGINT,
    amount DECIMAL(19,2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    payment_method_ref VARCHAR(255),
    request_idempotency_key VARCHAR(255),
    stripe_idempotency_key VARCHAR(255),
    stripe_payment_intent_id VARCHAR(255),
    status VARCHAR(50) NOT NULL DEFAULT 'RECEIVED',
    failure_code VARCHAR(255),
    failure_message VARCHAR(255),
    claimed_by VARCHAR(255),
    claimed_at DATETIME,
    version BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME,
    updated_at DATETIME,
    PRIMARY KEY (id),
    UNIQUE KEY uk_main_payment_id (main_payment_id),
    UNIQUE KEY uk_request_idempotency_key (request_idempotency_key),
    UNIQUE KEY uk_stripe_idempotency_key (stripe_idempotency_key),
    UNIQUE KEY uk_stripe_payment_intent_id (stripe_payment_intent_id),
    INDEX idx_payment_ops_status_claimed (status, claimed_by, claimed_at)
) ENGINE=InnoDB;

CREATE TABLE refund_operations (
    id BIGINT NOT NULL AUTO_INCREMENT,
    refund_id BIGINT,
    main_payment_id BIGINT,
    order_id BIGINT,
    amount DECIMAL(19,2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    external_payment_id VARCHAR(255),
    stripe_refund_id VARCHAR(255),
    request_idempotency_key VARCHAR(255),
    stripe_idempotency_key VARCHAR(255),
    status VARCHAR(50) NOT NULL DEFAULT 'RECEIVED',
    failure_code VARCHAR(255),
    failure_message VARCHAR(255),
    claimed_by VARCHAR(255),
    claimed_at DATETIME,
    version BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME,
    updated_at DATETIME,
    PRIMARY KEY (id),
    UNIQUE KEY uk_refund_id (refund_id),
    UNIQUE KEY uk_stripe_refund_id (stripe_refund_id),
    UNIQUE KEY uk_refund_request_idempotency_key (request_idempotency_key),
    UNIQUE KEY uk_refund_stripe_idempotency_key (stripe_idempotency_key),
    INDEX idx_refund_ops_status_claimed (status, claimed_by, claimed_at)
) ENGINE=InnoDB;

CREATE TABLE outbox_events (
    id BIGINT NOT NULL AUTO_INCREMENT,
    event_id VARCHAR(36) NOT NULL,
    aggregate_type VARCHAR(255),
    aggregate_id BIGINT,
    event_type VARCHAR(255),
    event_version INT NOT NULL DEFAULT 2,
    topic VARCHAR(255),
    event_key VARCHAR(255),
    payload TEXT,
    idempotency_key VARCHAR(255),
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    retry_count INT NOT NULL DEFAULT 0,
    max_retries INT NOT NULL DEFAULT 5,
    next_retry_at DATETIME,
    claimed_by VARCHAR(255),
    claimed_at DATETIME,
    created_at DATETIME,
    published_at DATETIME,
    last_error VARCHAR(255),
    PRIMARY KEY (id),
    UNIQUE KEY uk_event_id (event_id),
    UNIQUE KEY uk_outbox_idempotency_key (idempotency_key),
    INDEX idx_outbox_status_retry (status, next_retry_at, retry_count),
    INDEX idx_outbox_status_claimed (status, claimed_by, claimed_at)
) ENGINE=InnoDB;

CREATE TABLE processed_events (
    id BIGINT NOT NULL AUTO_INCREMENT,
    event_id VARCHAR(36),
    consumer_name VARCHAR(255),
    event_type VARCHAR(255),
    correlation_id VARCHAR(255),
    aggregate_id BIGINT,
    processed_at DATETIME,
    PRIMARY KEY (id),
    UNIQUE KEY uk_consumer_event (consumer_name, event_id),
    INDEX idx_processed_at (processed_at)
) ENGINE=InnoDB;
