FROM maven:3.8.1-openjdk-17

WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline -B

COPY src /app/src

EXPOSE 8082

CMD ["mvn", "spring-boot:run", "-DskipTests", "-Dspring-boot.run.jvmArguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"]
